# This workflow will run other workflows
name: Build (All)

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    uses: ./.github/workflows/build_linux.yml
  wnt:
    uses: ./.github/workflows/build_wnt.yml
