name: Build (Linux/GCC/qtk3+gtk4)
on:
  workflow_call:

jobs:
  linux-gcc-gtk3:
    runs-on: ubuntu-24.04
    steps:
    - name: Clone Tree
      uses: actions/checkout@v6
      with:
        path: occt-samples-gtk.git
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        # libtbb-dev is added as a workaround for broken CMake configuration files within libocct
        sudo apt-get update
        sudo apt-get install -y \
          g++ cmake ninja-build \
          libocct-visualization-dev libocct-modeling-data-dev \
          libocct-modeling-algorithms-dev libocct-foundation-dev \
          libgl-dev libegl-dev \
          libtbb-dev \
          libgtkmm-3.0-dev \
          xvfb scrot
    - name: Configure project
      run: |
        cmake -S "$GITHUB_WORKSPACE/occt-samples-gtk.git" -B "$GITHUB_WORKSPACE/occt-samples-gtk-make" -G Ninja \
              -D CMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/occt-samples-gtk" \
              -D GTK_VERSION=GTK3
    - name: Build project
      run: |
        cmake --build "$GITHUB_WORKSPACE/occt-samples-gtk-make" --config Release
    - name: Install project
      run: |
        cmake --build "$GITHUB_WORKSPACE/occt-samples-gtk-make" --config Release --target install
    - name: Run tests
      run: |
        xvfb-run --server-args="-screen 0 800x600x24" \
                 $GITHUB_WORKSPACE/occt-samples-gtk.git/.github/workflows/screenshot.sh \
                 $GITHUB_WORKSPACE/occt-samples-gtk/occt-gtk3-glarea $GITHUB_WORKSPACE/occt-samples-gtk/occt-sample-gtk3.png 5
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: occt-gtk3-linux
        path: occt-samples-gtk/*.png

  linux-gcc-gtk4:
    runs-on: ubuntu-24.04
    steps:
    - name: Clone Tree
      uses: actions/checkout@v6
      with:
        path: occt-samples-gtk.git
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        # libtbb-dev is added as a workaround for broken CMake configuration files within libocct
        sudo apt-get update
        sudo apt-get install -y \
          g++ cmake ninja-build \
          libocct-visualization-dev libocct-modeling-data-dev \
          libocct-modeling-algorithms-dev libocct-foundation-dev \
          libgl-dev libegl-dev \
          libtbb-dev \
          libgtkmm-4.0-dev \
          xvfb scrot
    - name: Configure project
      run: |
        cmake -S "$GITHUB_WORKSPACE/occt-samples-gtk.git" -B "$GITHUB_WORKSPACE/occt-samples-gtk-make" -G Ninja \
              -D CMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/occt-samples-gtk" \
              -D GTK_VERSION=GTK4
    - name: Build project
      run: |
        cmake --build "$GITHUB_WORKSPACE/occt-samples-gtk-make" --config Release
    - name: Install project
      run: |
        cmake --build "$GITHUB_WORKSPACE/occt-samples-gtk-make" --config Release --target install
    - name: Run tests
      run: |
        xvfb-run --server-args="-screen 0 800x600x24" \
                 $GITHUB_WORKSPACE/occt-samples-gtk.git/.github/workflows/screenshot.sh \
                 $GITHUB_WORKSPACE/occt-samples-gtk/occt-gtk4-glarea $GITHUB_WORKSPACE/occt-samples-gtk/occt-sample-gtk4.png 5
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: occt-gtk4-linux
        path: occt-samples-gtk/*.png
